version: "2.4"
services:
    proxy-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: proxy-nginx

        restart: always
        depends_on:
            - django-db
            - web-django
        volumes:
            - ./nginx/logs:/var/log/nginx
            - ./nginx/nginx.docker.conf:/etc/nginx/conf.d/default.conf
            - ./app/aleksan_site/static:/aleksan_site/static
        networks:
            - proxy-nginx
        ports:
            - 8888:80

    web-django:
        build:
            context: ./app/aleksan_site
            dockerfile: Dockerfile
        container_name: web-django
        env_file:
            - ./config/secret/.env
        restart: always
        volumes:
            - ./app/aleksan_site:/aleksan_site
        working_dir:
            /aleksan_site

        command: sh -c "python3 manage.py collectstatic --noinput && gunicorn --bind :5000 aleksan_site.wsgi:application"
        depends_on:
            django-db:
                condition: service_healthy
        networks:
            - proxy-nginx
            - db
        expose:
            - 5000


    django-db:
        image: postgres
        container_name: django-db
        env_file:
            - ./config/secret/.env.database
        restart: always
        healthcheck:
            test: psql --version || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/postgresql/data/
        networks:
            - db
        expose:
            - 5432


volumes:
    db_data:

networks:
    proxy-nginx:
        driver: bridge
    db:
        driver: bridge